[theme]
primaryColor = "#0675eb"          
backgroundColor = "#f9f9f9"      
secondaryBackgroundColor = "#fcfcfc" 
textColor = "#000000"
font = "sans serif"

[server]
headless = true
enableCORS = true
